### PR TITLE
add crunch.js into build

### PR DESCRIPTION
**Pull request by lavrton**

### CODE REVIEW

**Comment by lavrton** [comment]
added some bugs fixes

**Comment by lavrton** [comment]
Are you interested in some bugs fixed (see other commits in this pull request)? Should I create another pull request?

**Comment by julio-pixelements** [comment]
Yeah, sorry I'll see these bug fixes. Thank you!

**Comment by julio-pixelements** [comment]
I fixed these bugs. Thank you Lavrton.

**Pull request closed without merging**
